/**
 * Hub modal/form class tokens for Todo — styles live in todo-hub-theme.css.
 * Import these instead of duplicating Tailwind strings across modal components.
 */
export const TODO_HUB = {
  field: "todo-hub-field",
  fieldTitle: "todo-hub-field todo-hub-field--title",
  fieldGrow: "todo-hub-field todo-hub-field--grow",
  fieldComment: "todo-hub-field todo-hub-field--comment",
  fieldOnPanel: "todo-hub-field todo-hub-field--on-panel",
  label: "todo-hub-label",
  labelSection: "todo-hub-label todo-hub-label--section",
  labelHiddenMd: "todo-hub-label todo-hub-label--section todo-hub-label--hidden-md",
  panel: "todo-hub-panel",
  panelInset: "todo-hub-panel todo-hub-panel--inset",
  panelInsetCompact: "todo-hub-panel todo-hub-panel--inset todo-hub-panel--inset-compact",
  detailsSplit: "todo-hub-details-split",
  detailsSplitDescription: "todo-hub-details-split__description",
  detailsSplitComments: "todo-hub-details-split__comments",
  commentInputRow: "todo-hub-comment-input-row",
  btnSecondary: "todo-hub-btn-secondary",
  btnGhost: "todo-hub-btn-ghost",
  btnAttach: "todo-hub-btn-attach",
  dropzone: "todo-hub-dropzone",
  modalShell: "todo-hub-modal-shell",
  modalHeader: "todo-hub-modal-header",
  modalFooter: "todo-hub-modal-footer",
  statusTrack: "todo-hub-status-track",
  statusPill: "todo-hub-status-pill",
  statusBtn: "todo-hub-status-btn",
  statusBtnActive: "todo-hub-status-btn todo-hub-status-btn--active",
  attachmentRow: "todo-hub-attachment-row",
  attachmentThumb: "todo-hub-attachment-thumb",
  iconBtn: "todo-hub-icon-btn",
  iconBtnPlay: "todo-hub-icon-btn todo-hub-icon-btn--play",
  iconBtnDone: "todo-hub-icon-btn todo-hub-icon-btn--done",
  iconBtnCancel: "todo-hub-icon-btn todo-hub-icon-btn--cancel",
  iconBtnDanger: "todo-hub-icon-btn todo-hub-icon-btn--danger",
  filterPanel: "todo-hub-filter-panel",
  filterRow: "todo-hub-filter-row",
  /** Task modal Details — 4 filters on one row (distinct from board .todo-hub-filter-row flex). */
  taskDetailFilterRow: "todo-hub-task-detail-filter-row",
  /** Shared trigger chrome for task modal 2×2 filters. */
  taskDetailFilterTrigger: "w-full justify-between",
  /** Label + control stack in task modal filter grid. */
  taskDetailFilterCell: "todo-hub-task-detail-filter-cell",
  badge: "todo-hub-badge",
  badgePriorityLow: "todo-hub-badge todo-hub-badge--priority-low",
  badgePriorityMedium: "todo-hub-badge todo-hub-badge--priority-medium",
  badgePriorityHigh: "todo-hub-badge todo-hub-badge--priority-high",
  badgeProject: "todo-hub-badge todo-hub-badge--project",
  badgeMeta: "todo-hub-badge todo-hub-badge--meta",
  badgeCount: "todo-hub-badge todo-hub-badge--count",
  searchHighlight: "todo-search-highlight",
  taskCard: "todo-hub-task-card",
  taskCardHeader: "todo-hub-task-card__header",
  taskCardHeaderMain: "todo-hub-task-card__header-main",
  taskCardTitleRow: "todo-hub-task-card__title-row",
  taskCardTitle: "todo-hub-task-card__title",
  taskCardActions: "todo-hub-task-card__actions",
  taskCardBody: "todo-hub-task-card__body",
  taskCardBadges: "todo-hub-task-card__badges",
  taskCardBadgesLeft: "todo-hub-task-card__badges-left",
  taskCardBadgesRight: "todo-hub-task-card__badges-right",
  taskCardFooter: "todo-hub-task-card__footer",
  taskCardFooterMeta: "todo-hub-task-card__footer-meta",
  taskCardEmoji: "todo-hub-task-card__emoji",
  taskCardArchived: "todo-hub-task-card todo-hub-task-card--archived",
  taskCardHigh: "todo-hub-task-card todo-hub-task-card--high-priority",
  taskColumn: "todo-hub-column",
  statCard: "todo-hub-stat-card",
  metaChip: "todo-hub-meta-chip",
} as const;

export type TodoHubClassKey = keyof typeof TODO_HUB;
