-- P0020 Data Box — Kanban tasks schema (ported from P0019 Work Performance)
-- profiles table already exists (20260528170000_workspace_user_directory.sql)

-- ==============================================================
-- 1. ENUM TYPES
-- ==============================================================

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'task_status') THEN
    CREATE TYPE public.task_status AS ENUM ('todo', 'inprogress', 'done', 'cancelled');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'task_priority') THEN
    CREATE TYPE public.task_priority AS ENUM ('low', 'medium', 'high');
  END IF;
END $$;

-- ==============================================================
-- 2. TABLES
-- ==============================================================

CREATE TABLE IF NOT EXISTS public.projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  name text NOT NULL,
  created_by uuid REFERENCES public.profiles (id) ON DELETE SET NULL,
  color text
);

CREATE TABLE IF NOT EXISTS public.project_members (
  project_id bigint NOT NULL REFERENCES public.projects (id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (project_id, user_id)
);

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS default_project_id bigint;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_default_project' AND contype = 'f'
  ) THEN
    ALTER TABLE public.profiles
      ADD CONSTRAINT fk_default_project
      FOREIGN KEY (default_project_id)
      REFERENCES public.projects (id) ON DELETE SET NULL;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  created_by uuid REFERENCES public.profiles (id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  title text NOT NULL,
  description text,
  status public.task_status NOT NULL DEFAULT 'todo',
  priority public.task_priority NOT NULL DEFAULT 'medium',
  due_date date,
  project_id bigint REFERENCES public.projects (id) ON DELETE SET NULL,
  assignees jsonb NOT NULL DEFAULT '[]'::jsonb,
  project_ids bigint[] NOT NULL DEFAULT '{}'::bigint[]
);

CREATE INDEX IF NOT EXISTS idx_tasks_user_id ON public.tasks (user_id);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON public.tasks (status);
CREATE INDEX IF NOT EXISTS idx_tasks_project_id ON public.tasks (project_id);
CREATE INDEX IF NOT EXISTS idx_tasks_assignees ON public.tasks USING gin (assignees);

ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS assignees jsonb NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS project_ids bigint[] NOT NULL DEFAULT '{}'::bigint[];

CREATE TABLE IF NOT EXISTS public.task_attachments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id bigint NOT NULL REFERENCES public.tasks (id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  file_name text NOT NULL,
  file_path text NOT NULL,
  file_type text,
  file_size bigint,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_task_attachments_task_id ON public.task_attachments (task_id);

CREATE TABLE IF NOT EXISTS public.task_time_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id bigint NOT NULL REFERENCES public.tasks (id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  start_time timestamptz NOT NULL,
  end_time timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_task_time_logs_task_id ON public.task_time_logs (task_id);
CREATE INDEX IF NOT EXISTS idx_task_time_logs_user_id ON public.task_time_logs (user_id);

CREATE TABLE IF NOT EXISTS public.activity_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  user_id uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  task_id bigint REFERENCES public.tasks (id) ON DELETE SET NULL,
  action text NOT NULL,
  details jsonb
);

CREATE INDEX IF NOT EXISTS idx_activity_logs_user_id ON public.activity_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_task_id ON public.activity_logs (task_id);

CREATE TABLE IF NOT EXISTS public.task_comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  task_id bigint NOT NULL REFERENCES public.tasks (id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  content text NOT NULL CHECK (content <> '')
);

CREATE INDEX IF NOT EXISTS idx_task_comments_task_id ON public.task_comments (task_id);
CREATE INDEX IF NOT EXISTS idx_task_comments_user_id ON public.task_comments (user_id);

CREATE TABLE IF NOT EXISTS public.notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  user_id uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  actor_id uuid REFERENCES public.profiles (id) ON DELETE SET NULL,
  type text NOT NULL,
  data jsonb,
  is_read boolean NOT NULL DEFAULT false
);

-- ==============================================================
-- 3. FUNCTIONS & TRIGGERS
-- ==============================================================

CREATE OR REPLACE FUNCTION public.moddatetime()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS handle_updated_at ON public.tasks;
CREATE TRIGGER handle_updated_at
  BEFORE UPDATE ON public.tasks
  FOR EACH ROW EXECUTE FUNCTION public.moddatetime();

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, email, avatar_url, role, created_at, last_sign_in_at)
  VALUES (
    NEW.id,
    NEW.raw_user_meta_data ->> 'full_name',
    NEW.email,
    NEW.raw_user_meta_data ->> 'avatar_url',
    'employee',
    NEW.created_at,
    NEW.last_sign_in_at
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

CREATE OR REPLACE FUNCTION public.handle_user_update()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  UPDATE public.profiles
  SET last_sign_in_at = NEW.last_sign_in_at,
      email = NEW.email
  WHERE id = NEW.id;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_updated ON auth.users;
CREATE TRIGGER on_auth_user_updated
  AFTER UPDATE ON auth.users
  FOR EACH ROW
  WHEN (OLD.last_sign_in_at IS DISTINCT FROM NEW.last_sign_in_at OR OLD.email IS DISTINCT FROM NEW.email)
  EXECUTE FUNCTION public.handle_user_update();

CREATE OR REPLACE FUNCTION public.get_user_role(p_user_id uuid)
RETURNS text
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT coalesce(role, 'employee') FROM public.profiles WHERE id = p_user_id;
$$;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT public.get_user_role(auth.uid()) = 'admin';
$$;

CREATE OR REPLACE FUNCTION public.is_manager()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT public.get_user_role(auth.uid()) IN ('admin', 'manager');
$$;

CREATE OR REPLACE FUNCTION public.task_user_has_access(p_task_id bigint, p_user_id uuid)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_task public.tasks%ROWTYPE;
BEGIN
  SELECT * INTO v_task FROM public.tasks WHERE id = p_task_id;
  IF NOT FOUND THEN RETURN FALSE; END IF;
  IF v_task.user_id = p_user_id OR v_task.created_by = p_user_id THEN RETURN TRUE; END IF;
  IF EXISTS (
    SELECT 1 FROM jsonb_array_elements(COALESCE(v_task.assignees, '[]'::jsonb)) elem
    WHERE elem ->> 'user_id' = p_user_id::text
  ) THEN RETURN TRUE; END IF;
  IF v_task.project_id IS NOT NULL AND public.is_project_member(v_task.project_id, p_user_id) THEN
    RETURN TRUE;
  END IF;
  RETURN public.is_admin();
END;
$$;

CREATE OR REPLACE FUNCTION public.can_access_task_from_attachment_path(p_file_path text)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_task_id bigint;
BEGIN
  BEGIN
    v_task_id := (string_to_array(p_file_path, '/'))[2]::bigint;
  EXCEPTION WHEN OTHERS THEN
    RETURN FALSE;
  END;
  IF v_task_id IS NULL THEN RETURN FALSE; END IF;
  RETURN public.task_user_has_access(v_task_id, auth.uid());
END;
$$;

CREATE OR REPLACE FUNCTION public.is_project_member(p_project_id bigint, p_user_id uuid)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.project_members
    WHERE project_id = p_project_id AND user_id = p_user_id
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.create_new_task_assignment_notification()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  assigner_name text;
BEGIN
  SELECT full_name INTO assigner_name FROM public.profiles WHERE id = auth.uid();
  IF NEW.user_id IS NOT NULL AND NEW.user_id <> auth.uid() THEN
    INSERT INTO public.notifications (user_id, actor_id, type, data)
    VALUES (
      NEW.user_id, auth.uid(), 'new_task_assigned',
      jsonb_build_object('task_id', NEW.id, 'task_title', NEW.title, 'assigner_name', assigner_name)
    );
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_new_task_created_for_other ON public.tasks;
CREATE TRIGGER on_new_task_created_for_other
  AFTER INSERT ON public.tasks
  FOR EACH ROW EXECUTE FUNCTION public.create_new_task_assignment_notification();

DROP TRIGGER IF EXISTS on_task_reassigned ON public.tasks;
CREATE TRIGGER on_task_reassigned
  AFTER UPDATE OF user_id ON public.tasks
  FOR EACH ROW
  WHEN (OLD.user_id IS DISTINCT FROM NEW.user_id)
  EXECUTE FUNCTION public.create_new_task_assignment_notification();

CREATE OR REPLACE FUNCTION public.create_new_comment_notification()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  task_info RECORD;
  commenter_name text;
BEGIN
  SELECT user_id, created_by, title INTO task_info FROM public.tasks WHERE id = NEW.task_id;
  SELECT full_name INTO commenter_name FROM public.profiles WHERE id = NEW.user_id;

  IF task_info.user_id IS NOT NULL AND task_info.user_id <> NEW.user_id THEN
    INSERT INTO public.notifications (user_id, actor_id, type, data)
    VALUES (task_info.user_id, NEW.user_id, 'new_comment',
            jsonb_build_object('task_id', NEW.task_id, 'task_title', task_info.title, 'commenter_name', commenter_name));
  END IF;

  IF task_info.created_by IS NOT NULL
     AND task_info.created_by <> NEW.user_id
     AND task_info.created_by <> task_info.user_id THEN
    INSERT INTO public.notifications (user_id, actor_id, type, data)
    VALUES (task_info.created_by, NEW.user_id, 'new_comment',
            jsonb_build_object('task_id', NEW.task_id, 'task_title', task_info.title, 'commenter_name', commenter_name));
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_new_comment ON public.task_comments;
CREATE TRIGGER on_new_comment
  AFTER INSERT ON public.task_comments
  FOR EACH ROW EXECUTE FUNCTION public.create_new_comment_notification();

-- ==============================================================
-- 4. RLS
-- ==============================================================

ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_time_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_members ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can create tasks." ON public.tasks;
CREATE POLICY "Users can create tasks." ON public.tasks
  FOR INSERT WITH CHECK (auth.uid() = created_by);

DROP POLICY IF EXISTS "Users can view, update, delete tasks they are assigned to or created." ON public.tasks;
CREATE POLICY "Users can view, update, delete tasks they are assigned to or created." ON public.tasks
  FOR ALL USING (auth.uid() = user_id OR auth.uid() = created_by);

DROP POLICY IF EXISTS "Users can access tasks as json assignee." ON public.tasks;
CREATE POLICY "Users can access tasks as json assignee." ON public.tasks
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM jsonb_array_elements(COALESCE(tasks.assignees, '[]'::jsonb)) elem
      WHERE elem ->> 'user_id' = auth.uid()::text
    )
  );

DROP POLICY IF EXISTS "Users can view tasks in their projects." ON public.tasks;
CREATE POLICY "Users can view tasks in their projects." ON public.tasks
  FOR SELECT USING (project_id IS NULL OR public.is_project_member(project_id, auth.uid()));

DROP POLICY IF EXISTS "Admins can manage all tasks." ON public.tasks;
CREATE POLICY "Admins can manage all tasks." ON public.tasks
  FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Users can manage attachments for tasks they can access." ON public.task_attachments;
CREATE POLICY "Users can manage attachments for tasks they can access." ON public.task_attachments
  FOR ALL USING (public.task_user_has_access(task_id, auth.uid()));

DROP POLICY IF EXISTS "Admins can manage all attachments." ON public.task_attachments;
CREATE POLICY "Admins can manage all attachments." ON public.task_attachments
  FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Users can manage their own time logs." ON public.task_time_logs;
CREATE POLICY "Users can manage their own time logs." ON public.task_time_logs
  FOR ALL USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Admins can manage all time logs." ON public.task_time_logs;
CREATE POLICY "Admins can manage all time logs." ON public.task_time_logs
  FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Authenticated users can view all logs." ON public.activity_logs;
CREATE POLICY "Authenticated users can view all logs." ON public.activity_logs
  FOR SELECT USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Users can create logs for their own actions." ON public.activity_logs;
CREATE POLICY "Users can create logs for their own actions." ON public.activity_logs
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Admins can manage all logs." ON public.activity_logs;
CREATE POLICY "Admins can manage all logs." ON public.activity_logs
  FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Authenticated users can view all comments on accessible tasks." ON public.task_comments;
CREATE POLICY "Authenticated users can view all comments on accessible tasks." ON public.task_comments
  FOR SELECT USING (public.task_user_has_access(task_id, auth.uid()));

DROP POLICY IF EXISTS "Users can add comments." ON public.task_comments;
CREATE POLICY "Users can add comments." ON public.task_comments
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own comments." ON public.task_comments;
CREATE POLICY "Users can update their own comments." ON public.task_comments
  FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own comments." ON public.task_comments;
CREATE POLICY "Users can delete their own comments." ON public.task_comments
  FOR DELETE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Admins can manage all comments." ON public.task_comments;
CREATE POLICY "Admins can manage all comments." ON public.task_comments
  FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Users can view their own notifications." ON public.notifications;
CREATE POLICY "Users can view their own notifications." ON public.notifications
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own notifications." ON public.notifications;
CREATE POLICY "Users can update their own notifications." ON public.notifications
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Admins can manage all notifications." ON public.notifications;
CREATE POLICY "Admins can manage all notifications." ON public.notifications
  FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Admins can manage all projects." ON public.projects;
CREATE POLICY "Admins can manage all projects." ON public.projects
  FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Project members can view their projects." ON public.projects;
CREATE POLICY "Project members can view their projects." ON public.projects
  FOR SELECT USING (public.is_project_member(projects.id, auth.uid()));

DROP POLICY IF EXISTS "Admins can manage project members." ON public.project_members;
CREATE POLICY "Admins can manage project members." ON public.project_members
  FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Users can view their own project memberships." ON public.project_members;
CREATE POLICY "Users can view their own project memberships." ON public.project_members
  FOR SELECT USING (user_id = auth.uid());

DROP POLICY IF EXISTS "Managers can manage members of their own projects." ON public.project_members;
CREATE POLICY "Managers can manage members of their own projects." ON public.project_members
  FOR ALL USING (
    public.is_manager() AND public.is_project_member(project_members.project_id, auth.uid())
  );

-- ==============================================================
-- 5. STORAGE
-- ==============================================================

INSERT INTO storage.buckets (id, name, public)
VALUES ('task-attachments', 'task-attachments', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Users can view task attachments." ON storage.objects;
CREATE POLICY "Users can view task attachments." ON storage.objects
  FOR SELECT USING (bucket_id = 'task-attachments' AND public.can_access_task_from_attachment_path(name));

DROP POLICY IF EXISTS "Users can upload task attachments." ON storage.objects;
CREATE POLICY "Users can upload task attachments." ON storage.objects
  FOR INSERT WITH CHECK (
    bucket_id = 'task-attachments'
    AND auth.uid()::text = (storage.foldername(name))[1]
    AND public.can_access_task_from_attachment_path(name)
  );

DROP POLICY IF EXISTS "Users can delete their own task attachments." ON storage.objects;
CREATE POLICY "Users can delete their own task attachments." ON storage.objects
  FOR DELETE USING (
    bucket_id = 'task-attachments'
    AND auth.uid()::text = (storage.foldername(name))[1]
    AND public.can_access_task_from_attachment_path(name)
  );

DROP POLICY IF EXISTS "Admins can manage all task attachment objects." ON storage.objects;
CREATE POLICY "Admins can manage all task attachment objects." ON storage.objects
  FOR ALL USING (bucket_id = 'task-attachments' AND public.is_admin())
  WITH CHECK (bucket_id = 'task-attachments' AND public.is_admin());

-- Realtime
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'tasks'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.tasks;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'task_comments'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.task_comments;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'task_attachments'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.task_attachments;
  END IF;
END $$;

NOTIFY pgrst, 'reload schema';
